title: Abi Hassen; Website
author: abihassen
subtitle: A place for public projects and general information

footer_url: https://github.com/abihassen/abihassen.github.io.git
footer_text: "Abi Hassen 2020 ... forked from parchment by pro-panda"

profile-picture: assets/profilep.png
favicon_location: assets/favicon.png

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "index"
 - name: "Posts"
   link: "posts"
 - name: "CV"
   link: "/assets/cv.pdf"
