title: Abi Hassen; Website
author: abihassen
subtitle: A place for public projects and general information

url: "https://abihassen.github.io"
baseurl: "/"

footer_only_homepage: false
footer_url: "https://abihassen.com"
footer_text: "Abi Hassen 2020 ... Theme by pro-panda"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Posts"
   link: "posts"
 - name: "CV"
   link: "/assets/cv.pdf"
