title: Abi Hassen's Website
author: Abi Hassen
subtitle: This is my

url: "https://pro-panda.github.io"
baseurl: "/"

footer_only_homepage: true
footer_url: "https://abihassen.com"
footer_text: "Abi Hassen 2020 /n Theme by pro-panda"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: "https://pro-panda.github.io/resume.pdf"
